using Mars.Generators.ApplicationGenerators.Configurations.Global.TypedConfigurations;

namespace Mars.Generators.ApplicationGenerators.Configurations.Global;

public sealed class GlobalCqrsGeneratorConfiguration
{
    public string AutogeneratedFileText { get; set; } = null!;
    public bool NullableEnable { get; set; } = true;
    public string TemplatesBasePath { get; set; } = null!;
    public PutBusinessLogicIntoNamespaceConfiguration BusinessLogicNamespaceBasePath { get; set; } = null!;
    public PutEndpointsIntoNamespaceConfiguration EndpointsNamespaceBasePath { get; set; } = null!;
    public NameConfiguration FeatureNameConfiguration { get; set; } = null!;
}