namespace Mars.Generators.ApplicationGenerators.Configurations.Global;

public sealed class GlobalCqrsGeneratorConfiguration
{
    public string AutogeneratedFileText { get; set; } = null!;
    public bool NullableEnable { get; set; } = true;
    public string TemplatesBasePath { get; set; } = null!;
}