using Mars.Generators.ApplicationGenerators.Configurations.Global.TypedConfigurations;

namespace Mars.Generators.ApplicationGenerators.Configurations.Global.Factories;

public class GlobalCrudGeneratorConfigurationDefaultConfigurationFactory
{
    public static GlobalCqrsGeneratorConfiguration Construct()
    {
        return new GlobalCqrsGeneratorConfiguration
        {
            AutogeneratedFileText = @"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a crud generator tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------",
            NullableEnable = true,
            TemplatesBasePath = "Mars.Generators.Templates.Crud",
            BusinessLogicNamespaceBasePath =
                new PutBusinessLogicIntoNamespaceConfiguration(
                    "{{assembly_name}}.Application.{{feature_name}}.{{function_name}}"),
            EndpointsNamespaceBasePath =
                new PutEndpointsIntoNamespaceConfiguration("{{assembly_name}}.Endpoints.{{entity_name}}Endpoints"),
            FeatureNameConfiguration = new NameConfiguration("{{entity_name}}Feature")
        };
    }
}