namespace ITech.CrudGenerator.CrudGeneratorCore.Configurations.Global;

public sealed class GlobalCqrsGeneratorConfigurationBuilder
{
    public string AutogeneratedFileText { get; set; } = null!;
    public bool NullableEnable { get; set; } = true;

    public GlobalCqrsGeneratorConfiguration Build()
    {
        return new GlobalCqrsGeneratorConfiguration
        {
            AutogeneratedFileText = AutogeneratedFileText,
            NullableEnable = NullableEnable,
        };
    }
}