namespace ITech.CrudGenerator.CrudGeneratorCore.Configurations.Global;

internal class GlobalCrudGeneratorConfigurationFactory
{
    public static GlobalCrudGeneratorConfiguration Construct()
    {
        return new GlobalCrudGeneratorConfiguration(
            autogeneratedFileText: @"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a crud generator tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------",
            nullableEnable: true);
    }
}