using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

namespace ITech.CrudGenerator.Core.Generators.Core;

internal abstract class BaseGenerator
{
    public List<GeneratorResult> GeneratedFiles { get; protected set; } = [];
    protected readonly string AutogeneratedFileText;
    protected readonly bool NullableEnable;

    protected BaseGenerator(string autogeneratedFileText, bool nullableEnable)
    {
        AutogeneratedFileText = autogeneratedFileText;
        NullableEnable = nullableEnable;
    }

    public abstract void RunGenerator();

    protected virtual void WriteFile(string className, string code)
    {
        var sb = new StringBuilder();
        sb.AppendLine(AutogeneratedFileText);
        if (NullableEnable)
        {
            sb.AppendLine("#nullable enable");
        }

        sb.AppendLine(code);

        var sourceCode = sb.ToString().Trim();

        var result = CSharpSyntaxTree.ParseText(SourceText.From(sourceCode, Encoding.UTF8))
            .GetRoot()
            .NormalizeWhitespace()
            .SyntaxTree
            .GetText();

        GeneratedFiles.Add(new GeneratorResult($"{className}.g.cs", result));
    }
}

public class GeneratorResult
{
    public string FileName { get; }
    public SourceText Source { get; }

    public GeneratorResult(string fileName, SourceText source)
    {
        FileName = fileName;
        Source = source;
    }
}