namespace ITech.CrudGenerator.Core.Configurations.Global;

public sealed record GlobalCrudGeneratorConfiguration {
    public string AutogeneratedFileText { get; set; } = null!;
    public bool NullableEnable { get; set; } = true;

    public GlobalCrudGeneratorConfiguration(string autogeneratedFileText, bool nullableEnable) {
        AutogeneratedFileText = autogeneratedFileText;
        NullableEnable = nullableEnable;
    }
}