//HintName: CreateEntityCustomHandler.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a crud generator tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using Teniry.Cqrs.Commands;
using Teniry.CrudGenerator.Tests;
using Teniry.CrudGenerator.Tests;
using Mapster;

namespace Teniry.CrudGenerator.Tests.Application.TestEntityFeature.CreateCustomNs;
public partial class CreateEntityCustomHandler : ICommandHandler<CreateEntityCustomCommand, CreatedCustomDto>
{
    private readonly TestDb _db;
    public CreateEntityCustomHandler(TestDb db)
    {
        _db = db;
    }

    /// <inheritdoc/>
    public async Task<CreatedCustomDto> HandleAsync(CreateEntityCustomCommand command, CancellationToken cancellation)
    {
        var entity = command.Adapt<TestEntity>();
        await _db.AddAsync(entity, cancellation);
        await _db.SaveChangesAsync(cancellation);
        return new CreatedCustomDto(entity.Id);
    }
}