//HintName: AddTestEntityCommand.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a crud generator tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Teniry.CrudGenerator.Tests.Application.TestEntityFeature.AddTestEntity;
/// <summary>
///     Create Test entity
/// </summary>
/// <returns>Returns id of created entity of type <see cref = "CreatedTestEntityDto"/></returns>
public partial class AddTestEntityCommand
{
    public string Name { get; set; } = "";
}