//HintName: AddTestEntityEndpoint.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a crud generator tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using Microsoft.AspNetCore.Mvc;
using Teniry.Cqrs.Commands;
using Teniry.CrudGenerator.Tests.Application.TestEntityFeature.AddTestEntity;

namespace Teniry.CrudGenerator.Tests.Endpoints.TestEntityEndpoints;
public static partial class AddTestEntityEndpoint
{
    /// <summary>
    ///     Create Test entity
    /// </summary>
    /// <response code="201">New Test entity created</response>
    [ProducesResponseType(201)]
    public static async Task<IResult> AddAsync(AddTestEntityCommand command, ICommandDispatcher commandDispatcher, CancellationToken cancellation)
    {
        var result = await commandDispatcher.DispatchAsync<AddTestEntityCommand, CreatedTestEntityDto>(command, cancellation);
        return TypedResults.Created($"", result);
    }
}