//HintName: DelEntityCustomHandler.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a crud generator tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using Teniry.Cqrs.Commands;
using Teniry.CrudGenerator.Tests;
using Teniry.CrudGenerator.Tests;

namespace Teniry.CrudGenerator.Tests.Application.TestEntityFeature.DelCustomNs;
public partial class DelEntityCustomHandler : ICommandHandler<DelEntityCustomCommand>
{
    private readonly TestDb _db;
    public DelEntityCustomHandler(TestDb db)
    {
        _db = db;
    }

    /// <inheritdoc/>
    public async Task HandleAsync(DelEntityCustomCommand command, CancellationToken cancellation)
    {
        var entity = await _db.FindAsync<TestEntity>(new object[] { command.Id }, cancellation);
        if (entity == null)
        {
            return;
        }

        _db.Remove(entity);
        await _db.SaveChangesAsync(cancellation);
    }
}