//HintName: DelEntityCustomCommand.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a crud generator tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Teniry.CrudGenerator.Tests.Application.TestEntityFeature.DelCustomNs;
/// <summary>
///     Delete Test entity
/// </summary>
/// <returns>Nothing</returns>
public partial class DelEntityCustomCommand
{
    public int Id { get; set; }

    public DelEntityCustomCommand(int id)
    {
        Id = id;
    }
}