//HintName: DelCustomEndpoint.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a crud generator tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using Microsoft.AspNetCore.Mvc;
using Teniry.Cqrs.Commands;
using Teniry.CrudGenerator.Tests.Application.TestEntityFeature.DelCustomNs;

namespace Teniry.CrudGenerator.Tests.Endpoints.TestEntityEndpoints;
public static partial class DelCustomEndpoint
{
    /// <summary>
    ///     Delete Test entity
    /// </summary>
    /// <response code="204">Test entity deleted</response>
    [ProducesResponseType(204)]
    public static async Task<IResult> RunDelAsync(int id, ICommandDispatcher commandDispatcher, CancellationToken cancellation)
    {
        var command = new DelEntityCustomCommand(id);
        await commandDispatcher.DispatchAsync<DelEntityCustomCommand>(command, cancellation);
        return TypedResults.NoContent();
    }
}