//HintName: fetchTestEntityEndpoint.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a crud generator tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using Microsoft.AspNetCore.Mvc;
using Teniry.Cqrs.Queries;
using Teniry.CrudGenerator.Tests.Application.TestEntityFeature.fetchTestEntity;

namespace Teniry.CrudGenerator.Tests.Endpoints.TestEntityEndpoints;
public static partial class fetchTestEntityEndpoint
{
    /// <summary>
    ///     Get Test entity by id
    /// </summary>
    /// <response code="200">Returns full Test entity data</response>
    [ProducesResponseType(typeof(TestEntityDto), 200)]
    public static async Task<IResult> fetchAsync(int id, IQueryDispatcher queryDispatcher, CancellationToken cancellation)
    {
        var query = new fetchTestEntityQuery(id);
        var result = await queryDispatcher.DispatchAsync<fetchTestEntityQuery, TestEntityDto>(query, cancellation);
        return TypedResults.Ok(result);
    }
}