//HintName: FetchTestEntityHandler.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a crud generator tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using Teniry.Cqrs.Queries;
using Teniry.Cqrs.Extended.Exceptions;
using Teniry.CrudGenerator.Tests;
using Teniry.CrudGenerator.Tests;
using Mapster;

namespace Teniry.CrudGenerator.Tests.Application.TestEntityFeature.FetchTestEntity;
public partial class FetchTestEntityHandler : IQueryHandler<FetchTestEntityQuery, TestEntityDto>
{
    private readonly TestDb _db;
    public FetchTestEntityHandler(TestDb db)
    {
        _db = db;
    }

    /// <inheritdoc/>
    public async Task<TestEntityDto> HandleAsync(FetchTestEntityQuery query, CancellationToken cancellation)
    {
        var entity = await _db.FindAsync<TestEntity>(new object[] { query.Id }, cancellation);
        if (entity == null)
        {
            throw new EntityNotFoundException(typeof(TestEntity));
        }

        return entity.Adapt<TestEntityDto>();
    }
}