//HintName: TestEntitiesDto.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a crud generator tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using Teniry.Cqrs.Extended.Queryables.Page;

namespace Teniry.CrudGenerator.Tests.Application.TestEntityFeature.FetchTestEntities;
public partial class TestEntitiesDto : PagedResult<TestEntitiesListItemDto>
{
    public TestEntitiesDto(List<TestEntitiesListItemDto> items, PageInfo page) : base(items, page)
    {
    }
}