//HintName: FetchTestEntitiesQuery.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a crud generator tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using Teniry.Cqrs.Extended.Queryables.Page;
using Teniry.Cqrs.Extended.Queryables.Sort;

namespace Teniry.CrudGenerator.Tests.Application.TestEntityFeature.FetchTestEntities;
/// <summary>
///     Get Test entities
/// </summary>
/// <returns>Returns Test entities of type <see cref = "TestEntitiesDto"/></returns>
public partial class FetchTestEntitiesQuery : IDefineSortable, IPage
{
    public int[]? Ids { get; set; }
    public string? Name { get; set; }
    /// <inheritdoc/>
    public int Page { get; set; }
    /// <inheritdoc/>
    public int PageSize { get; set; }
    /// <inheritdoc/>
    public string[]? Sort { get; set; }

    /// <inheritdoc/>
    public string[] GetSortKeys()
    {
        return new string[]
        {
            "id",
            "name"
        };
    }
}