//HintName: TestEntitiesListItemDto.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a crud generator tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Teniry.CrudGenerator.Tests.Application.TestEntityFeature.GetTestEntities;
public partial class TestEntitiesListItemDto
{
    public int Id { get; set; }
    public string Name { get; set; } = "";
}