//HintName: CreateTestEntityHandler.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a crud generator tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using Teniry.Cqrs.Commands;
using Teniry.CrudGenerator.Tests;
using Teniry.CrudGenerator.Tests;
using Mapster;

namespace Teniry.CrudGenerator.Tests.Application.TestEntityFeature.CreateTestEntity;
public partial class CreateTestEntityHandler : ICommandHandler<CreateTestEntityCommand, CreatedTestEntityDto>
{
    private readonly TestDb _db;
    public CreateTestEntityHandler(TestDb db)
    {
        _db = db;
    }

    /// <inheritdoc/>
    public async Task<CreatedTestEntityDto> HandleAsync(CreateTestEntityCommand command, CancellationToken cancellation)
    {
        var entity = command.Adapt<TestEntity>();
        await _db.AddAsync(entity, cancellation);
        await _db.SaveChangesAsync(cancellation);
        return new CreatedTestEntityDto(entity.Id);
    }
}