//HintName: CreatedTestEntityDto.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a crud generator tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Teniry.CrudGenerator.Tests.Application.TestEntityFeature.CreateTestEntity;
public partial class CreatedTestEntityDto
{
    public int Id { get; set; }

    public CreatedTestEntityDto(int id)
    {
        Id = id;
    }
}