//HintName: UpdateTestEntityCommand.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a crud generator tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using Teniry.Cqrs.Extended.Exceptions;

namespace Teniry.CrudGenerator.Tests.Application.TestEntityFeature.UpdateTestEntity;
/// <summary>
///     Update Test entity
/// </summary>
/// <returns>Nothing</returns>
/// <exception cref = "EntityNotFoundException">When Test entity entity does not exist</exception>
public partial class UpdateTestEntityCommand
{
    public int Id { get; set; }
    public string Name { get; set; } = "";

    public UpdateTestEntityCommand(int id)
    {
        Id = id;
    }
}