//HintName: PatchTestEntityCommand.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a crud generator tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using Teniry.Cqrs.Extended.Exceptions;
using Teniry.Cqrs.Extended.Types.PatchOperationType;

namespace Teniry.CrudGenerator.Tests.Application.TestEntityFeature.PatchTestEntity;
/// <summary>
///     Patch Test entity
/// </summary>
/// <returns>Nothing</returns>
/// <exception cref = "EntityNotFoundException">When Test entity entity does not exist</exception>
public partial class PatchTestEntityCommand
{
    public int Id { get; set; }
    public PatchOp<string?>? ResetableName { get; set; }

    public PatchTestEntityCommand(int id)
    {
        Id = id;
    }
}