//HintName: UpddCustomEndpoint.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a crud generator tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using Microsoft.AspNetCore.Mvc;
using Teniry.Cqrs.Commands;
using Mapster;
using Teniry.CrudGenerator.Tests.Application.TestEntityFeature.UpdCustomNs;

namespace Teniry.CrudGenerator.Tests.Endpoints.TestEntityEndpoints;
public static partial class UpddCustomEndpoint
{
    /// <summary>
    ///     Patch Test entity
    /// </summary>
    /// <response code="204">Test entity updated</response>
    [ProducesResponseType(204)]
    public static async Task<IResult> RunUpdAsync(int id, PatchTestEntityVm vm, ICommandDispatcher commandDispatcher, CancellationToken cancellation)
    {
        var command = new UpdEntityCustomCommand(id);
        vm.Adapt(command);
        await commandDispatcher.DispatchAsync<UpdEntityCustomCommand>(command, cancellation);
        return TypedResults.NoContent();
    }
}