//HintName: UpdCustomVm.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a crud generator tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using Teniry.Cqrs.Extended.Types.PatchOperationType;

namespace Teniry.CrudGenerator.Tests.Endpoints.TestEntityEndpoints;
public partial class UpdCustomVm
{
    public PatchOp<string>? Name { get; set; }
}