//HintName: GeneratedEndpointsMapExtension.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a crud generator tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using Teniry.CrudGenerator.Tests.Endpoints.TestEntityEndpoints;

namespace AutogeneratedEndpoints;
public static class GeneratedEndpointsMapExtension
{
    public static void MapGeneratedEndpoints(this WebApplication app)
    {
        app.MapPut("/testEntity/{id}/upd", UpdTestEntityEndpoint.UpdAsync).WithTags("Test entity");
    }
}