//HintName: UpdTestEntityHandler.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a crud generator tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using Teniry.Cqrs.Commands;
using Teniry.Cqrs.Extended.Exceptions;
using Teniry.CrudGenerator.Tests;
using Teniry.CrudGenerator.Tests;
using Mapster;

namespace Teniry.CrudGenerator.Tests.Application.TestEntityFeature.UpdTestEntity;
public partial class UpdTestEntityHandler : ICommandHandler<UpdTestEntityCommand>
{
    private readonly TestDb _db;
    public UpdTestEntityHandler(TestDb db)
    {
        _db = db;
    }

    /// <inheritdoc/>
    public async Task HandleAsync(UpdTestEntityCommand command, CancellationToken cancellation)
    {
        var entity = await _db.FindAsync<TestEntity>(new object[] { command.Id }, cancellation);
        if (entity == null)
        {
            throw new EntityNotFoundException(typeof(TestEntity));
        }

        command.Adapt(entity);
        await _db.SaveChangesAsync(cancellation);
    }
}