namespace Mars.Generators.CrudGeneratorCore.Configurations.Global;

public sealed class GlobalCqrsGeneratorConfigurationBuilder
{
    public string AutogeneratedFileText { get; set; } = null!;
    public bool NullableEnable { get; set; } = true;
    public string TemplatesBasePath { get; set; } = null!;

    public GlobalCqrsGeneratorConfiguration Build()
    {
        return new GlobalCqrsGeneratorConfiguration
        {
            AutogeneratedFileText = AutogeneratedFileText,
            NullableEnable = NullableEnable,
            TemplatesBasePath = TemplatesBasePath
        };
    }
}