namespace ITech.CrudGenerator.CrudGeneratorCore.Configurations.Global.Factories;

internal class GlobalCrudGeneratorConfigurationDefaultConfigurationFactory
{
    public static GlobalCqrsGeneratorConfiguration Construct()
    {
        return new GlobalCqrsGeneratorConfiguration(
            autogeneratedFileText: @"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a crud generator tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------",
            nullableEnable: true);
    }
}