using System.Collections.Generic;
using System.Linq;
using Mars.Generators.ApplicationGenerators.Core;
using Mars.Generators.ApplicationGenerators.Core.DbContextCore;
using Mars.Generators.ApplicationGenerators.Core.EntityCustomizationSchemeCore;
using Mars.Generators.ApplicationGenerators.Core.EntitySchemaCore;
using Mars.Generators.ApplicationGenerators.Generators;
using Microsoft.CodeAnalysis;

namespace Mars.Generators.ApplicationGenerators;

[Generator]
public class AppGenerator : ISourceGenerator
{
    public void Initialize(GeneratorInitializationContext context)
    {
        context.RegisterForSyntaxNotifications(() => new EntityGeneratorConfigurationSyntaxReceiver());
    }

    public void Execute(GeneratorExecutionContext context)
    {
        if (context.SyntaxReceiver is not EntityGeneratorConfigurationSyntaxReceiver syntaxReceiver) return;

        var dbContextScheme = DbContextSchemeFactory.Construct(context);

        List<EndpointMap> endpointsMaps = new();
        var configuration = new CrudGeneratorConfiguration();

        foreach (var classSyntax in syntaxReceiver.ClassesForCrudGeneration)
        {
            var (entityGeneratorConfigurationSymbol, entitySymbol) = classSyntax.AsSymbol(context);

            var entityCustomizationScheme = EntityCastomizationSchemeFactory
                .Construct(entityGeneratorConfigurationSymbol as INamedTypeSymbol, context);
            var entityScheme = EntitySchemeFactory.Construct(entitySymbol, entityCustomizationScheme, dbContextScheme);

            var generateGetByIdQuery = new GetByIdQueryCrudGenerator(
                context,
                entitySymbol,
                configuration.GetByIdQueryGenerator,
                entityScheme,
                dbContextScheme);
            generateGetByIdQuery.RunGenerator();
            if (generateGetByIdQuery.EndpointMap is not null)
            {
                endpointsMaps.Add(generateGetByIdQuery.EndpointMap);
            }

            var generateListQuery = new ListQueryCrudGenerator(
                context,
                entitySymbol,
                configuration.GetListQueryGenerator,
                entityScheme,
                dbContextScheme);
            generateListQuery.RunGenerator();
            if (generateListQuery.EndpointMap is not null)
            {
                endpointsMaps.Add(generateListQuery.EndpointMap);
            }

            var generateCreateCommand = new CreateCommandCrudGenerator(
                context,
                entitySymbol,
                configuration.CreateCommandCommandGenerator,
                entityScheme,
                dbContextScheme);
            generateCreateCommand.RunGenerator();
            if (generateCreateCommand.EndpointMap is not null)
            {
                endpointsMaps.Add(generateCreateCommand.EndpointMap);
            }

            var generateUpdateCommand = new UpdateCommandCrudGenerator(
                context,
                entitySymbol,
                configuration.UpdateCommandCommandGenerator,
                entityScheme,
                dbContextScheme);
            generateUpdateCommand.RunGenerator();
            if (generateUpdateCommand.EndpointMap is not null)
            {
                endpointsMaps.Add(generateUpdateCommand.EndpointMap);
            }

            var generateDeleteCommand = new DeleteCommandCrudGenerator(
                context,
                entitySymbol,
                configuration.DeleteCommandCommandGenerator,
                entityScheme,
                dbContextScheme);
            generateDeleteCommand.RunGenerator();
            if (generateDeleteCommand.EndpointMap is not null)
            {
                endpointsMaps.Add(generateDeleteCommand.EndpointMap);
            }
        }

        var mapEndpointsGenerator = new MapEndpointsGenerator(context, endpointsMaps, configuration);
        mapEndpointsGenerator.RunGenerator();
    }
}

internal class MapEndpointsGenerator : BaseGenerator
{
    private readonly List<EndpointMap> _endpointsMaps;
    private readonly CrudGeneratorConfiguration _configuration;
    private readonly string _endpointMapsClassName;

    public MapEndpointsGenerator(
        GeneratorExecutionContext context,
        List<EndpointMap> endpointsMaps,
        CrudGeneratorConfiguration configuration)
        : base(context,
            configuration.AutogeneratedFileText,
            configuration.NullableEnable)
    {
        _endpointsMaps = endpointsMaps;
        _configuration = configuration;
        _endpointMapsClassName = "GeneratedEndpointsMapExtension";
    }

    public override void RunGenerator()
    {
        var usings = _endpointsMaps.Select(x => x.EndpointNamespace).Distinct().Select(x => $"using {x};");
        var maps = _endpointsMaps
            .Select(x =>
                $"app.Map{x.HttpMethod}(\"{x.EndpointRoute}\", {x.FunctionCall}).WithTags(\"{x.EntityName}\");")
            .ToList();
        var model = new
        {
            Usings = string.Join("", usings),
            PutIntoNamespace = "Mars.Api",
            ExtensionClassName = _endpointMapsClassName,
            Maps = string.Join("", maps)
        };
        WriteFile(
            $"{_configuration.TemplatesBasePath}.GeneratedEndpointsMapExtension.txt",
            model,
            _endpointMapsClassName);
    }
}